### ISSUE TITLE
Minifying and Compressing Javascript

### ISSUE THREAD

**Issue by kenleezle** [BranchMetrics/Web-SDK#14] opened 2015-03-05 20:00 UTC
I have an infrastructure in place to concatenate, minify, and then gzip all of my javascript dependencies into one single app file. Could you indicate in your docs how to fit your sdk into a framework like this.

Usually this would work by having a script include, but you seem to have embedded inside of your quick start, which won't work.

Any Ideas? Thanks.

**Comment by kenleezle** [comment] 2015-03-05 20:12
And while we are on the topic, how do you use the gzip provided in the bower package?

**Comment by dmitrig01** [comment] 2015-03-05 20:28
hey @kenleezle – are you using any sort of standardized module loader? or just concatinating the files?

the script loader is actually entirely optional. you are free to include `dist/branch.js` directly in your script, and branch will work as intended – the script is just a quick way to get started

**Comment by kenleezle** [comment] 2015-03-05 20:32
@dmitrig01 great, so if i include branch.js, i can skip to the branch.init step?

**Comment by kenleezle** [comment] 2015-03-05 20:36
i am using browserify and loading modules using "require."

**Comment by dmitrig01** [comment] 2015-03-05 20:39
Ah, cool. It *should* work with require, but we haven't tested it extensively yet.

You will still need to call branch.init; however, you won't need this part:

```
(function(b,r,a,n,c,h,_,s,d,k){if(!b[n]||!b[n]._q){for(;s<_.length;)c(h,_[s++]);d=r.createElement(a);d.async=1;d.src="dist/branch.js";k=r.getElementsByTagName(a)[0];k.parentNode.insertBefore(d,k);b[n]=h}})(window,document,"script","branch",function(b,r){b[r]=function(){b._q.push([r,arguments])}},{_q:[],_v:1},"init data setIdentity logout track link sendSMS referrals credits redeem banner".split(" "),0);
```

**Comment by dmitrig01** [comment] 2015-03-05 20:46
are you using bower or another package manager?

**Comment by kenleezle** [comment] 2015-03-05 20:48
i installed with bower.
browserify is unable to find the module

**Comment by kenleezle** [comment] 2015-03-05 20:52
While i've got you, do you know a trick to get the banner back after you've x'd it? Branch seems to remember that i've x'd it and is not showing me the banner anymore, even though i've cleared my cache.

**Comment by kenleezle** [comment] 2015-03-05 20:55
OK, i've got it working without require, but including the javascript in the normal fashion which makes a branch variable globally available. thanks a lot for your help and you can close this issue. if you do know a trick to make branch forget you x'd the banner tell me though ;) tell mike i said thanks too.

**Comment by scotthasbrouck** [comment] 2015-03-05 20:55
Hey @kenleezle jumping in here to help you with the banner... The banner disables itself after it has been shown by default. The idea is that if a user closes it, they wont want to see it again. For testing purposes, just clear session storage with sessionStorage.clear() in your console. Would it be helpful for me to include an option that disables not showing the banner a second time?

**Comment by dmitrig01** [comment] 2015-03-05 20:57
@kenleezle Ah! The version on Bower is old :-(. We'll publish a new versino in the next 15 mins or so, and then we can test. If that still doesn't mind, I'd love to hop on a call with you to get it working if you wouldn't mind – this is super important to us!

**Comment by kenleezle** [comment] 2015-03-05 21:02
@scotthasbrouck yes that would be helpful, a banner option right? i perused the banner options to solve my problem initially. i did not peruse the other api calls for a solution. sessionStorage.clear() worked like a charm. thank you.

**Comment by kenleezle** [comment] 2015-03-05 21:03
@dmitrig01 i will test the new version when it comes out since you guys jumped right on my initial issue and i appreciate that.

**Comment by kenleezle** [comment] 2015-03-05 21:03
just let me know when its ready

**Comment by scotthasbrouck** [comment] 2015-03-05 21:04
@kenleezle perfect, that's an easy addition. I'll have the updated Bower package momentarily, and will add the banner option right after that... stay tuned!

**Comment by dmitrig01** [comment] 2015-03-05 22:34
Just released a new, working bower version (I think! it works for me...)

I'll open a separate issue for the banner thing. @kenleezle, if the bower install is working now, can you close this issue?

**Comment by kenleezle** [comment] 2015-03-05 22:47
yep, i'll test the require as well right now

**Comment by kenleezle** [comment] 2015-03-05 23:02
i installed using npm, did require('branch-sdk') and then browserified and it worked like a charm! :gem:  nice job! closing issue!

**Closed** 2015-03-05 23:02 UTC

**Comment by dmitrig01** [comment] 2015-03-05 23:04
awesome!!
